# Generated by Django 5.1.3 on 2025-10-23 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
